language: node_js
node_js:
  - '10'
sudo: required
dist: trusty
addons:
  chrome: stable
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  # - export CHROME_BIN=chromium-browser
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
install:
  - yarn add codecov -g
  - yarn ci
script:
  # run build script specified in package.json
  - yarn ci
  # call script for deploying of produced artifacts
  # - bash ./.travis-deploy.sh
after_success:
  - codecov